Error when creating a report from the Facility Search Page
gaepdit/FMS pull request #193
Opened 2022-02-16 19:57 UTC by tom-karasch

Originally when clicking the **Create Report** button on the **Facility Search** page sent you to the **Report** page giving the user a preview of the report to be sent to Excel, along with the search criteria. However, in production the app failed to go to the **Report** page and brought up a login screen instead, which did not work. 
So, to correct the problem, temporarily, instead of sending the user to the report page, the user now sees the button, renamed **Export to Excel** and directly generates the report file ( a **.csv** file of the requested Facility Detailed List).

2022-02-21 19:44 UTC, dougwaldron requested changes
@tom-karasch Good start on this, and I agree this is the best way to address this issue. Besides avoiding the original authorization bug, it will remove a step for the user along with the server overhead of pulling the same data twice on the Reports page. 

Please address the following issues with the current PR:

1. The exported spreadsheet does not match the search results. You're creating a new, empty `FacilitySpec` for the report instead of using the existing `Spec` property that represents the user's  search criteria. Did you look at this?

2. Delete all commented out code. Commented code doesn't add value and distorts the version control code diffs.

3. Delete the "Report" page; it's no longer used.

4. In the body of your PR comment, add the following line. This links the PR with the original issue so that merging the PR will automatically close it.

    `fixes #192`

By the way, you don't need to create a new branch or PR or anything when you implement these fixes. Any additional commits you push to this branch will automatically update this PR.

2022-02-21 19:44 UTC, dougwaldron commented on FMS/Pages/Facilities/Index.cshtml.cs
> +        public FacilitySpec ReportSpec { get; set; }
Don't create a new `FacilitySpec` property here. Bind the existing `Spec` instead.

2022-02-21 19:44 UTC, dougwaldron commented on FMS/Pages/Facilities/Index.cshtml.cs
> +        public IReadOnlyList<FacilityDetailDto> FacilityReportList { get; private set; }
Since this property is only used in the `OnPostAsync` method, move it there as a local variable instead.

2022-02-23 18:26 UTC, tom-karasch commented
Corrections to initial Reporting fix.
Removed "Report" Page and folder from Project.
Fixed use of Public property "Spec" and removed commented code.
Changed "Export" Button and changed "Get" to "Post" in HTML.

fixes #192

2022-02-23 20:45 UTC, dougwaldron approved these changes
Thanks! I can confirm that the export matches the search results. This is ready for QA.

A couple minor cleanup items: Not sure how it happened, but instead of deleting the Report page files, you just hid them from the VS project. I'll fix that shortly.

I also noticed that we no longer need to disable search form inputs when clicking the export button. I've fixed that as well.

2022-02-23 21:01 UTC, tom-karasch commented
Thanks, Doug.
I did not realize that the search form inputs were disabled after Export. 
I assumed removing the Report page from the project would mean that they are no longer published. I would like to revisit the export preview Page when adding direct to ".xls" format. So, I didn't see the harm in removing them from the project without deleting them. 
So, now I will Merge the pull request.
Should I then publish to both Dev and UAT or just UAT?

2022-02-23 21:01 UTC, merged

2022-02-23 21:13 UTC, dougwaldron commented
Oh, I see. You're right that the report page wouldn't publish once it's removed from the project. But still, leaving them in is just like leaving in commented code. If you ever want to restore those files, just revert commit 66e272a7755adc879f7a7647026f284c85cf6c7d.

Go ahead and publish to dev and send to Tamika for QA. Thanks.